### ISSUE TITLE
abandon the message to stderr in dump error

### ISSUE THREAD

**Issue by tamada** [tamada/gibo-wrapper#16]
In running `gibo-wrapper dump UNKOWN-BOILERPLATE`, `gibo-wrapper` should print the error message from `gibo` to `stderr`.
However, `gibo-wrapper` prints no error message to stderr.

```sh
$ gibo dump UNKNOWN-BOILERPLATE
2024/11/30 09:08:14 On dumping UNKNOWN-BOILERPLATE: UNKNOWN-BOILERPLATE: boilerplate not found
$ gibo-wrapper dump UNKNOWN-BOILERPLATE 
$ # no messages are printed.
```

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the `perform_dump` function and the `main` function to properly handle and print error messages from gibo to stderr. This ensures that when an unknown boilerplate is requested, the error message is displayed as expected.

You can review changes in this commit: https://github.com/mnmnk43434/tamada-gibo-wrapper-16/commit/e971f451a92dd2514539b3516397b82a25465896.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
